version: '2'
services:
    paymentrequesttracker-app:
        image: paymentrequesttracker
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:sqlserver://paymentrequesttracker-mssql:1433;database=PaymentRequestTracker
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    paymentrequesttracker-mssql:
        extends:
            file: mssql.yml
            service: paymentrequesttracker-mssql
